### ISSUE TITLE
client/css/custom.bootstrap.less:498:22: Less compiler error: variable @link-hover-decoration is undefined

### ISSUE THREAD

**Issue by rdewolff** [Nemo64/meteor-bootstrap#17]
Hi all

Am wroking with your meteor-bootstrap module but, since yesterday, a new error happened which I can't seem to understand why : 

```
While Building the application:
client/css/custom.bootstrap.less:498:22: Less compiler error: variable @link-hover-decoration is undefined
```

Anyone got an idea why this happens and how to fix it properly? 

Thanks!

**Comment by ssullere29** [comment]
Thanks Nemo64 for the diff on variables.less
