### ISSUE TITLE
Using your package inside another package

### ISSUE THREAD

**Issue by vjau** [Nemo64/meteor-bootstrap#25]
Hi everyone.
I'm currently trying to put ALLl my app code inside packages.
That means my html templates are in packages too, so i think i need a root package that depends on nemo64:meteor-bootstrap for them to be able to use bootstrap.
However i have not been able to make it work so far.
If this is possible, what is the correct way to write a package whose only role is to correctly import this package for other packages with my app templates to consume.
Thank you very much.

**Comment by YuukanOO** [comment]
Is there any solution to this issue? When put inside my own package, it complains about `'../../../../../../../../../../data/marco/Git/meteor/white-universe/packages/nemo64:bootstrap/bootstrap/less/variables.less' wasn't found`

I found a folder named `data/` in my home folder, but it's empty.

**Comment by jindrichbartek** [comment]
For me worked to create my special separate own package 'common-libs' and setup this bootstrap package inside it. Then I just added common-libs package dependency to all my own packages, where I can now use shared bootstrap config, less, templates, etc.
