### ISSUE TITLE
SCSS conflicts

### ISSUE THREAD

**Issue by rafaelfaria** [Nemo64/meteor-bootstrap#35]
All my css files are written in scss, therefore i'm running the [fourseven:scss package](https://github.com/fourseven/meteor-scss) thing is that I think it conflicts, because it doesnt load bootstrap into the page.

I know so, because if i remove it, bootstrap is back on the page.

Any way to fix this?

Thanks

**Comment by emgee3** [comment]
Hey @rafaelfaria I can't seem to reproduce this. If you provide a cloneable reproduction, I'll be happy to look into it.

**Comment by emgee3** [comment]
Closing because no reproduction. Feel free to reopen with one.
