### ISSUE TITLE
Source map

### ISSUE THREAD

**Issue by dbernhard** [Nemo64/meteor-bootstrap#36]
Thanks for this great package. My source map happens to be off. The line numbers are wrong. I'm not sure if it's a bug or if I'm missing something obvious. Any thoughts?

Thanks!
db

**Comment by Helmi** [comment]
Same happened to me, too - i also wonder if this package will be updated to the lastest bootstrap version anytime soon or if it's probably a better idea to fork it.

**Comment by simison** [comment]
@Helmi instead of forking, shouldn't you consider pull request?

**Comment by dbernhard** [comment]
I think this is actually a bug in the meteor core. What seems to happen is that source maps get a bit messed up when the css files are concatenated and more than one package uses a similar source map path. See https://github.com/meteor/meteor/issues/3304#issuecomment-69846313 If you're using `@include` in any of your stylesheets, that will force a concatenation and trigger the bug.

I find that if you remove the `@include`s, it works properly. That's a huge pain and sort of defeats the point of less, but that's where we're at right now.

**Comment by webkenny** [comment]
@simison I'm happy to do the update to this library and issue a pull request. Do we know if this is still an active project?

**Comment by dbernhard** [comment]
@webkenny I think you're right: this package isn't regularly maintained. But as you say, it works perfectly so it's understandable.

**Comment by simison** [comment]
https://github.com/Nemo64/meteor-bootstrap/issues/30#issuecomment-68498777

**Comment by simison** [comment]
@Nemo64 perhaps you could open a call for maintainers and add them as contributors?

**Comment by Nemo64** [comment]
It would help. What do you mean by "a call for maintainers"? I'm a little inexperienced with managing repositories. I'd gladly take help maintaining this package.

**Comment by webkenny** [comment]
Hi @Nemo64. Great work on this package. @simison means putting inside your README.md that you are looking for co-maintainers of the package and allowing them to have contribute access to help you with pull requests and general maintenance. I know, for one, I'd be more than willing to assist. In the meantime, I'll go ahead and update Bootstrap to 3.3.2 and issue a pull for it.

**Comment by emgee3** [comment]
Hey all, I'm helping maintain this now. Ping me if you need a PR looked at. In the meantime, since this looks like a Meteor bug, I'm going to close this.
