### ISSUE TITLE
Please update to new version.

### ISSUE THREAD

**Issue by serkandurusoy** [Nemo64/meteor-bootstrap#38]
Cross reference:
https://github.com/Nemo64/meteor-bootstrap-data/issues/2

**Comment by guaka** [comment]
+1

**Comment by awgneo** [comment]
+1

**Comment by krishprasadar** [comment]
+1

**Comment by greglgomez** [comment]
+1

**Comment by serkandurusoy** [comment]
Ping! bootstrap@3.3.4 is now released

**Comment by simison** [comment]
Someone create a pull request?

**Comment by simison** [comment]
Done with https://github.com/Nemo64/meteor-bootstrap/pull/41

Thanks @emgee3 !

**Comment by slickdev** [comment]
Updated and getting the following error:

=> Errors prevented startup:                  
   
   While building the application:
   client/lib/custom.bootstrap.less:1518:18: Less compiler error: variable
   @form-group-margin-bottom is undefined

**Comment by emgee3** [comment]
You're welcome @simison 

@slickdev I had the same issue. Thanks for sharing your fix. This is because of the underlying Bootstrap changes. 

It might be helpful to make an upgrading note in the Readme. I'll accept a PR.
