### ISSUE TITLE
Make jQuery optional

### ISSUE THREAD

**Issue by idris** [Nemo64/meteor-bootstrap#39]
I'm using ReactJS with Meteor and would like to avoid including jQuery on the page.  There should be an option such that if I don't use any of the Bootstrap JS functionality, it doesn't include jQuery.

**Comment by emgee3** [comment]
@idris Makes sense, but Meteor's templating system uses jQuery events, so you have a hard dependency on jQuery, regardless of this package's usage.

**Comment by emgee3** [comment]
I looked into this a little more and right now blaze requires jquery (see https://github.com/meteor/meteor/blob/devel/packages/blaze/package.js#L8), and blaze is included with meteor-platform. 

It also looks like this isn't going to always be this way, but for now, it looks like we're stuck with jquery. So with that, I would prefer to not make this change now. 

Feel free to reopen if I've missed something.
