### ISSUE TITLE
root maybe not the best place

### ISSUE THREAD

**Issue by Maxhodges** [Nemo64/meteor-bootstrap#40]
I have a theme with a CSS which needs to load after the bootstrap theme in order to have precedence. Why do you build the LESS in the root? Wouldn't it be better in public? Is there some place where I can change the build target directory? Or do I just need to fork the project to do that?

**Comment by Nemo64** [comment]
If im not mistaken, the less files are created wherever the json file is. If you put the json file in Public, this package will generate everything there.

**Comment by emgee3** [comment]
The LESS files are indeed created in the same path as `custom.bootstrap.json`, which one can put in a subdirectory. If I've misunderstood the problem, we can reopen, but I'm closing for now.

**Comment by Maxhodges** [comment]
excellent! yes sorry I understand now. very helpful! great package; I'm recommending it to others.
