### ISSUE TITLE
A recent minor update to 3.3.4_1 gives an error

### ISSUE THREAD

**Issue by niranjans** [Nemo64/meteor-bootstrap#42]
Hi, 

I just updated my app and I am getting the following error:
```
   While building the application:
   client/lib/custom.bootstrap.less:1629:18: Less compiler error: variable @form-group-margin-bottom is undefined
````

I tried to comment that out and also delete the `custom.bootstrap.less` completely so that it could be generated again. But it still throws that error.

Is there something that I need to change?

Thanks

**Comment by Levino** [comment]
Same here.

**Comment by emgee3** [comment]
This occurs when upgrading the Bootstrap package. The underlying LESS variables changed between Bootstrap 3.x.x and 3.3.4, so your original  `custom.bootstrap.import.less` file does not contain the variable that was introduced in Bootstrap 3.3.4.

So what you have to do is **either**:

 - Delete `custom.bootstrap.import.less` and recreate your customized changes
or
 - Update `custom.bootstrap.import.less` to reflect the Bootstrap changes. Here's a screenshot of what changes are needed:

![screen shot 2015-03-31 at 4 43 56 pm](https://cloud.githubusercontent.com/assets/871917/6931746/918c93c0-d7c5-11e4-9e70-7e42c14d07af.png)

I have to think a bit on the best way of doing these upgrades, but for now, I'm liking to this issue in the README.md file.

**Comment by niranjans** [comment]
Got it. That worked. Thanks!

**Comment by raghuugare** [comment]
Was about to let you know about this issue--thanks for the fix friends! :)

**Comment by CaptSaltyJack** [comment]
HEY GUYS, I FOUND A MAJ—oh never mind. ;)
Thanks for the solution.

**Comment by KrishnaPG** [comment]
Just a quick question - I am new to these css/bootstrap/nemo stuff - what is the best way to configure these things? Because I think I have made some changes in my "custom.bootstrap.import.less" earlier (do not remember which ones) - now If I delete that file it gets created correctly, but may loose my changes - so what is the right "closed for modifications but open for extensions" way? 

Afterall this `less` stuff is supposed to help extensibility without having to manual tweaking, right?

I can see that there is a manual 'update' workaround given above - but just in case in future if these kind of things happen it is better to be organized from the start - so wondering whats the best way to go about it.

**Comment by KrishnaPG** [comment]
Alright - looks like I got something working. Moved all (and only) my custom changes into a separate `overrides.import.less` file and imported it as the last line of the auto-generated `custom.bootstrap.import.less`. The plan is to override the variables without modifying them *inplace* - and it seems to be working. 

This way I can have the auto-generated and override versions separate - where by the `custom.bootstrap.import.less` can be deleted and auto-generated anytime, except that only I need to add the extra line at the bottom whenever it is generated afresh. 

Perhaps, the nemo author could implement this solution - where he could add an empty `overrides.import.less` file in the directory and add the line for its import at the end of generated file.

Or if there is more better way to separate the auto-generated parts from customary changes - would love to follow it - please share.

**Comment by niranjans** [comment]
@KrishnaPG No actually, the `custom.bootstrap.import.less` is not meant to be deleted and auto-generated. There should be this in the top of the file - 
```
// This File is for you to modify!
// It won't be overwritten as long as it exists.
// You may include this file into your less files to benefit from
// mixins and variables that bootstrap provides.
```

So you can change your `@brand-primary` color and other things in this file and it won't be over-written. You can also then import this file into your other `less` files by placing this line on top - 
`@import "client/lib/custom.bootstrap.import.less";`

**Comment by KrishnaPG** [comment]
Well - one of the posts from the above says this:
`Delete custom.bootstrap.import.less and recreate your customized changes or`.

What is the guarantee that this kind of situation does not occur again, with say bootstrap 5, 6 ... 10 ??

And please do not ask me to follow the alternative of `manually updating an automatically generated file` - that's Software engineering going in the wrong direction.

**Comment by emgee3** [comment]
@KrishnaPG Pull requests welcome
