### ISSUE TITLE
what are the fields "alert" and "button" for?

### ISSUE THREAD

**Issue by cneuro** [Nemo64/meteor-bootstrap#47]
In `custom.bootstrap.json`, nothing changes in the generated CSS, nor are Bootstrap button or alert components affected, when these two fields are set to either `true` or `false`;

```javascript
// ...
"alert"    : true,
"button"   : true,
// ...
```

What are they for? And how are they different to the existing `alerts` and `buttons` fields?

Cheers

**Comment by emgee3** [comment]
Hey @cneuro , that's a good question!

From `affix` down through `transition`, those options are to add the Bootstrap JavaScript files, which you can do on a fairly fine-grained basis. So alert is https://github.com/twbs/bootstrap/blob/master/js/alert.js and button adds https://github.com/twbs/bootstrap/blob/master/js/button.js to your project.

It is pretty unclear, but changing the names at this point would break backwards compatibility and adding comments to the JSON file is non-standard.

I'll probably make some notes in the README next update.

Hope this helps!

**Comment by cneuro** [comment]
Hi there,

thanks very much for the clarification. I should have known that it was
targeting the JS stuff. It's interesting that one can add all the styling
of the alerts and buttons but not have any JS. It isn't clear to me from
the Bootstrap source what it actually does.

Anyway thanks again for your speedy and exemplarily patient and polite
response.

Cheers!
