### ISSUE TITLE
Meteor 1.2

### ISSUE THREAD

**Issue by simison** [Nemo64/meteor-bootstrap#55]
New and exciting stuff coming up!

http://info.meteor.com/blog/whats-coming-in-meteor-12-and-beyond
>More flexible is about deeper, richer hooks into the build process for plugin authors. This opens up new opportunities for package authors to extend Meteor, like an awesomely integrated way to do custom Bootstrap builds right from inside your Meteor codebase, or linters (code style checkers) that you drop into your app just by adding a package. It also allows us to fix a long-standing limitation with LESS includes that required an awkward workaround.

**Comment by emgee3** [comment]
This will be nice. My job no longer has me working much in Meteor, so a new Bootstrap integration sounds especially good (no need to maintain an awkward workaround).

**Comment by emgee3** [comment]
Also this got merged into devel today https://github.com/meteor/meteor/commit/52e6b38ea19f44ac1395e2ceaa736b338ad6c93d

**Comment by simison** [comment]
Closing, continue at #64 #66
