### ISSUE TITLE
Please update to 3.3.5 (cross post)

### ISSUE THREAD

**Issue by serkandurusoy** [Nemo64/meteor-bootstrap#56]
This is a cross post from https://github.com/Nemo64/meteor-bootstrap-data/issues/4

**Comment by emgee3** [comment]
This has now been updated. Please see https://github.com/Nemo64/meteor-bootstrap#upgrading

**Comment by serkandurusoy** [comment]
Hm, I guess this should be applied individually to each project and it seems the script has to be run within the same folder as the custom.bootstrap.less file.

Would it not be easier if you've just published an updated version on atmosphere?

**Comment by serkandurusoy** [comment]
Yikes! I *am terribly sorry*. I just realized that you've actually updated on atmosphere *and gone the extra mile* to mitigate upgrade issues.

Kudos! :clap:

**Comment by emgee3** [comment]
Haha, no worries. The wording was a bit stupid, in retrospect. I've clarified it a bit.
