### ISSUE TITLE
problem with bootstrap 3 3 5 1 and meteor 1 1 0 2

### ISSUE THREAD

**Issue by br9191fr** [Nemo64/meteor-bootstrap#59]
First of all Thanks for this great package

However I got some problem when trying to use it with bootstrap 3 3 5 1 and meteor 1 1 0 2

in the custom.bootstrap.json config file I must keep these settings to avoid error with the less compiler

"forms":		false,
"buttons":              false,
"button-groups":        false,
"input-groups":         false,
"navbar":               false,
"jumbotron":            false,
"modals":               false,
All others settings are OK (can choose true or false)

I try to run the two patchs files as suggested but no success at all

Do you have any hints ?

Thanks in advance

**Comment by tanis2000** [comment]
Can you provide the less compiler error?

**Comment by emgee3** [comment]
Is this an upgrade or a new install? You will need to post some code and the exact error message if we're going to have enough information to help.

**Comment by br9191fr** [comment]
@tanis2000 @emgee3 

Thanks for your replies 
It was an update of meteor to the latest version 1.1.0.2  

I solved it by adding some additional parameters in custom.bootstrap.import.less and the error disappear

@btn-border-radius-base:         5;
@btn-border-radius-small:        5;
@btn-border-radius-large:        5;

@form-group-margin-bottom:       15px;
@zindex-modal-background:  #333; ?? what is the correct value ?? 1050 ?
@jumbotron-heading-font-size:    ceil((@font-size-base * 2.0));

I think these parameters are new in bootstrap 3.3.5  Am I right or wrong

However is it possible to integrate them in the package ?

Thanks in advance

**Comment by emgee3** [comment]
That's what https://github.com/Nemo64/meteor-bootstrap#upgrading is for, though it will only upgrade 3.3.4 to 3.3.5. 

Glad you figured it out.
