### ISSUE TITLE
Tooltips Are Not Disabled When `"tooltip": false`

### ISSUE THREAD

**Issue by msolters** [Nemo64/meteor-bootstrap#60]
The Bootstrap CSS for `.tooltip` class is included whether or not `"tooltip": false` or `"tooltip": true` in `custom.bootstrap.json`.  This is a problem because the Bootstrap CSS for these features is overriding all the tooltips I have implemented using a different package, in direct contradiction with the fact that the Bootstrap tooltip feature has been explicitly configured to be disabled.

**Comment by emgee3** [comment]
Do you have `popover` enabled?

`tooltip.less` is included if `popover` is enabled. This may be a mistake, but it looks like the `tooltip.js` is required if `popover.js` is included. I can fix this, I'm just a bit worried if there will be some side effects.

**Comment by msolters** [comment]
I do have `popover` enabled!  I understand now.

The difficulty is that there will be side effects either way.  For example, I am making use of the [lookback:tooltips](https://github.com/lookback/meteor-tooltips) smart package, which gets more or less completely broken when Bootstrap's `.tooltip` class is overwriting the opacity to always be 0.  But as you point out, the side effects of strictly disabling tooltips might break `popovers`.

The only solution I can think of is to somehow namespace the Bootstrap `.tooltip` class so that it does not interfere with just anything containing the `.tooltip` class alone.  Something like `.bs-tooltip` or `.bs .tooltip`?  But then we're diverging from the Bootstrap syntax...

My personal solution was just to get rid of Bootstrap entirely and rewrite the functionality I needed from scratch, but that's not really a solution :confused:

**Comment by emgee3** [comment]
(Huh, I never knew if you commit using "Fixes (link to github issue)" in the description, it will automatically note that fact and close the issue.)

Looking into this a bit more, when using popover while you do need tooltip.js, from what I can tell you, you do not need the tooltip LESS. So I have removed it.

**Comment by msolters** [comment]
Awesome!

Yeah there's a lot of cool stuff you can do through Github commits.  If you haven't heard of or seen it before, you should definitely take a look at [waffle.io](http://waffle.io).  It's one of the first places I was introduced to Github's built in keyword filters, and it's a very very useful tool for tracking bugs.  It's built on top of this issue tracker here.
