### ISSUE TITLE
Upgrading causes error in custom.bootstrap.less due to missing var from ..import.less

### ISSUE THREAD

**Issue by AndreasGalster** [Nemo64/meteor-bootstrap#61]
Just upgraded to the new version of your package and got an error because variable was missing in the custom.bootstra.import.less file for @btn-border-radius-base. I'm guessing there were more errors here, anyway I quickly "fixed" the issue by deleting the import.less file and have a new one auto-generated. 

So yea, upgrading is a problem because you don't get all the new variables that might be available I suppose?

**Comment by emgee3** [comment]
Yes, though this is documented already and there's a upgrade script (see https://github.com/Nemo64/meteor-bootstrap#upgrade-problems). Suggestions welcome on how to make this more recognizable.
