### ISSUE TITLE
client/lib/custom.bootstrap.less:1121:3: Less compiler error: .input-lg is undefined

### ISSUE THREAD

**Issue by MarcTe** [Nemo64/meteor-bootstrap#62]
client/lib/custom.bootstrap.less:1121:3: Less compiler error: .input-lg is undefined

**Comment by emgee3** [comment]
See https://github.com/Nemo64/meteor-bootstrap#upgrade-problems and if that doesn't handle it, delete `custom.bootstrap.import.less` and restart meteor.
