### ISSUE TITLE
Bootstrap js is not being loaded

### ISSUE THREAD

**Issue by fgarci03** [Nemo64/meteor-bootstrap#67]
This may be something I did wrong...

But after a clean install of this package, the bootstrap js files were not being loaded... But, the less and fonts were. Even by installing bootstrap-data directly, I can't find the js files anywhere.

Has this happened to anyone else?
I'm using meteor@1.3.2.4

Thanks

**Comment by simison** [comment]
See https://github.com/Nemo64/meteor-bootstrap#upgrade-problems

**Comment by fgarci03** [comment]
Thanks. Since the problem was different from what's stated in the upgrading guide, I assumed it was for meteor@1.2 and lower, not higher :)
